### ISSUE TITLE
You might not need ReasonReact.NoUpdate

### ISSUE THREAD

**Issue by arecvlohe** [thangngoc89/reason-react-router#1]
Thanks for having this example as a reference for others to use. It helped me to setup my router in no time. The only thing that changed for me was the `ReasonReact.NoUpdate` called inside of `didMount`.

https://github.com/thangngoc89/reason-react-router/blob/8f4a4f44571fe98073cd6e42b206fedb935ec7ed/src/Router.re#L16

https://github.com/thangngoc89/reason-react-router/blob/8f4a4f44571fe98073cd6e42b206fedb935ec7ed/src/Router.re#L20

I changed `ReasonReact.NoUpdate` to `()` and I stopped receiving compile errors about returning a `unit` type. I am not sure what this exactly means but I thought I would leave a note here in case anyone experiences the same issue.

**Comment by thangngoc89** [comment]
@arecvlohe you are using a newer version of Reasonreact

**Comment by arecvlohe** [comment]
I am using this version: `"reason-react": "^0.4.2"`

**Comment by thangngoc89** [comment]
@arecvlohe yep. that is what I meant. I using reason-react@0.3.2 . Whatever works for  you as long as the compiler doesn't complain
